fac.fac_config.*:
  type: config_entity
  label: 'Fast Autocomplete configuration'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    searchPluginId:
      type: string
      label: 'Search Plugin ID'
    searchPluginConfig:
      type: string
      label: 'Search Plugin config'
    inputSelectors:
      type: text
      label: 'Input selectors'
    numberOfResults:
      type: integer
      label: 'Number of results'
    emptyResult:
      type: text
      label: 'Empty result'
    viewModes:
      type: sequence
      label: 'View modes'
      sequence:
        type: string
        label: 'View mode'
    keyMinLength:
      type: integer
      label: 'Minimum key length'
    keyMaxLength:
      type: integer
      label: 'Maximum key length'
    allResultsLink:
      type: boolean
      label: 'All results link'
    allResultsLinkThreshold:
      type: integer
      label: 'All results link threshold'
    breakpoint:
      type: integer
      label: 'Breakpoint'
    resultLocation:
      type: string
      label: 'Result location'
    highlightingEnabled:
      type: boolean
      label: 'Highlighting enabled'
    anonymousSearch:
      type: boolean
      label: 'Anonymous search'
    cleanUpFiles:
      type: boolean
      label: 'Clean up files'
    filesExpiryTime:
      type: string
      label: 'Files expiry time'
